name: TruffleHog Secret Scanning
on:
  pull_request:
    branches:
      - develop
      - main

permissions: 
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: bash 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.63.1
      with:
        base: ${{ github.event.pull_request.base.sha }}
        head: ${{ github.event.pull_request.head.sha }}
        extra_args: --results=verified,unknown
