name: TruffleHog Secret Scanning
on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.90.8
        continue-on-error: true
        with:
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --log-level=2 --results=verified,unknown,unverified

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
